AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
Metrics/ClassLength:
  Exclude:
    - 'lib/calligraphy/resource/resource.rb'
    - 'lib/calligraphy/resource/file_resource.rb'
Metrics/AbcSize:
  Exclude:
    - 'lib/calligraphy/rails/mapper.rb'
Metrics/LineLength:
  Exclude:
    - 'lib/calligraphy/rails/mapper.rb'
Metrics/MethodLength:
  Exclude:
    - 'lib/calligraphy/rails/mapper.rb'
Style/ClassVars:
  Enabled: False
Style/DocumentationMethod:
  Enabled: True
